// styles/dailyWrite.styles.ts

import { StyleSheet } from "react-native";
import { Colors } from "../constants/Colors";
import { tokens } from "../constants/dailyWrite.constants";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F6F8FA" },
  header: {
    paddingTop: 50,
    textAlign: "center",
    fontSize: 28,
    fontWeight: "bold",
    letterSpacing: 0.5,
    textShadowColor: "rgba(60, 120, 200, 0.10)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    marginBottom: 8,
  },
  light: {
    position: "absolute",
    width: 600,
    height: 600,
    borderRadius: 300,
    opacity: 0.2,
  },
  light1: { backgroundColor: "#A7BFDE", top: -100, left: -150 },
  light2: { backgroundColor: "#7f9cf5", bottom: -150, right: -200 },
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 30,
    justifyContent: "space-between",
    paddingBottom: 40,
  },
  mainContent: { justifyContent: "center", flex: 1 },
  card: {
    borderRadius: tokens.radiusLg,
    paddingVertical: 24,
    paddingHorizontal: 20,
    backgroundColor: tokens.glassBg,
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: "rgba(93,161,217,0.15)",
    ...tokens.shadow,
  },
  moodCard: { marginBottom: 30 },
  title: {
    fontSize: 22,
    fontWeight: "600",
    color: Colors.light.text,
    textAlign: "center",
    marginBottom: 24,
  },
  moodBlock: { alignItems: "center" },
  moodImage: {
    width: 100,
    height: 100,
    resizeMode: "contain",
    marginBottom: 16,
  },
  moodLabel: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    minHeight: 32,
  },
  slider: { width: "100%", height: 40 },
  promptCard: { flexDirection: "row", alignItems: "center" },
  promptText: {
    flex: 1,
    fontSize: 16,
    color: Colors.light.softText,
    marginLeft: 16,
  },
  promptFilled: { color: Colors.light.text, fontWeight: "500" },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 56,
    borderRadius: tokens.radiusLg,
    marginTop: 24,
    shadowColor: tokens.tintMain,
    shadowOpacity: 0.15,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  saveText: { color: "#fff", fontSize: 18, fontWeight: "bold", marginLeft: 10 },

  // 🎯 Gereksiz AI buton stilleri kaldırıldı
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 120,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalContent: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 24,
    shadowColor: "#1A202C",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 30,
    elevation: 20,
    alignItems: "center",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: 24,
  },
  modalIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 18,
  },
  modalIconGradient: {
    flex: 1,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.7)",
  },
  modalBackButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(240, 245, 255, 0.6)",
  },
  modalTitleContainer: {
    alignItems: "center",
    marginBottom: 24,
    width: "100%",
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#1A202C",
    textAlign: "center",
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
    maxWidth: "90%",
  },
  modalDivider: {
    height: 1,
    backgroundColor: "rgba(93, 161, 217, 0.1)",
    marginVertical: 10,
    width: "25%",
    alignSelf: "center",
  },
  inputWrapper: {
    marginBottom: 10, // Biraz boşluk azalt
    width: "100%",
  },
  charCounter: { // YENİ STİL
    textAlign: "right",
    fontSize: 12,
    color: "#A0AEC0",
    marginTop: 4,
    paddingRight: 8,
  },
  inputContainer: {
    borderWidth: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 2,
    shadowColor: Colors.light.tint,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 14,
    fontSize: 15,
    color: "#1A1F36",
    minHeight: 110,
    textAlignVertical: "top",
    lineHeight: 22,
    letterSpacing: -0.2,
  },
  inputDecoration: {
    height: 1,
    position: "absolute",
    bottom: 0,
    left: "15%",
    right: "15%",
  },
  modalConfirmButton: {
    height: 54,
    width: "100%",
    borderRadius: 20,
    marginTop: 8,
    borderWidth: 1.5,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  modalConfirmButtonText: {
    fontSize: 17,
    fontWeight: "600",
    letterSpacing: -0.2,
    marginLeft: 8,
  },
  // 🎯 ScrollView için yeni stiller
  modalScrollView: {
    flex: 1,
    maxHeight: 350, // Maksimum yükseklik
    marginTop: 8,
  },
  modalScrollContent: {
    paddingBottom: 20,
    paddingHorizontal: 4,
  },
  modalText: {
    fontSize: 15,
    color: "#4A5568",
    lineHeight: 22,
    letterSpacing: -0.2,
    textAlign: "left", // Sol hizalama daha okunabilir
  },
  premiumPrompt: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  premiumCard: {
    width: "100%",
    maxWidth: 340,
    borderRadius: 28,
    padding: 24,
    alignItems: "center",
    shadowColor: "#1A202C",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 30,
    elevation: 20,
  },
  premiumHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  premiumTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#FFFFFF",
    marginLeft: 10,
  },
  premiumDescription: {
    fontSize: 15,
    color: "#E2E8F0",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 22,
  },
  premiumUsage: {
    fontSize: 14,
    color: "#E2E8F0",
    marginBottom: 20,
  },
  premiumButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 54,
    width: "100%",
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
  },
  premiumButtonText: {
    fontSize: 17,
    fontWeight: "600",
    color: "#6366F1",
    marginRight: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
});
